### PR TITLE
configure code coverage

### PR DESCRIPTION
**Pull request by 0mars**

### CODE REVIEW

**Comment by stephrdev** [comment]
Hi! Thank you for your pull request.

The code coverage configuration is already part of setup.cfg (https://github.com/stephrdev/cookiecutter-django-package/blob/master/%7B%7Bcookiecutter.package_name%7D%7D/setup.cfg#L17-L26).

I'm not sure if we should add all these debugging excludes to the settings as I don't think they should be present anyway ;-) To you have any additional arguments to understand your plan to add these?

**Comment by 0mars** [comment]
makes sense, thanks for pointing those out, I'm pretty new to the whole setup, just trying to make it work with coverage as defined. I updated the PR with the html directory location as it's not defined anywhere

**Comment by stephrdev** [comment]
This is actually not needed at all, htmlcov is the default for coverage :-)

**Comment by 0mars** [comment]
I did mypy support, if you'd like to me to open a PR, let me know. Thanks a lot!
Cheers!

**Comment by stephrdev** [comment]
If you happen do build the mypy support optional I'd really like to see a PR. Closing this one as coverage stuff is ok so far. Thanks!

**Pull request closed without merging**
